version: '3'
services:
  jenkins:
    build: .
    ports:
      - '8080:8080'
    volumes:
     - jenkins_demo:/var/lib/jenkins
    environment:
      - ADMIN_USER=jenkins
      - ADMIN_PASSWORD=jenkins
      - PIPELINE_LIBRARY_REMOTE=https://github.com/allianz-de/cidemo-pipeline-library.git

volumes:
  jenkins_demo:
